version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_server
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: poetry run uvicorn devnotes.main:app --host 0.0.0.0 --reload
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend


  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

# для визуального интерфейса
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
          - .env
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
