"""create initial tables

Revision ID: 64097374481b
Revises: 2a84ac416690
Create Date: 2025-05-24 09:58:22.378058

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "64097374481b"
down_revision: Union[str, None] = "2a84ac416690"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
